/*
  Warnings:

  - The values [TECHNICAL_OFFICE] on the enum `Role` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Role_new" AS ENUM ('CITIZEN', 'ADMINISTRATOR', 'PUBLIC_RELATIONS', 'CULTURE_EVENTS_TOURISM_SPORTS', 'LOCAL_PUBLIC_SERVICES', 'EDUCATION_SERVICES', 'PUBLIC_RESIDENTIAL_HOUSING', 'INFORMATION_SYSTEMS', 'MUNICIPAL_BUILDING_MAINTENANCE', 'PRIVATE_BUILDINGS', 'INFRASTRUCTURES', 'GREENSPACES_AND_ANIMAL_PROTECTION', 'WASTE_MANAGEMENT', 'ROAD_MAINTENANCE', 'CIVIL_PROTECTION');
ALTER TABLE "public"."User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING ("role"::text::"Role_new");
ALTER TYPE "Role" RENAME TO "Role_old";
ALTER TYPE "Role_new" RENAME TO "Role";
DROP TYPE "public"."Role_old";
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'CITIZEN';
COMMIT;
