export interface MunicipalityUserRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  role:
    | "ADMINISTRATOR"
    | "PUBLIC_RELATIONS"
    | "CULTURE_EVENTS_TOURISM_SPORTS"
    | "LOCAL_PUBLIC_SERVICES"
    | "EDUCATION_SERVICES"
    | "PUBLIC_RESIDENTIAL_HOUSING"
    | "INFORMATION_SYSTEMS"
    | "MUNICIPAL_BUILDING_MAINTENANCE"
    | "PRIVATE_BUILDINGS"
    | "INFRASTRUCTURES"
    | "GREENSPACES_AND_ANIMAL_PROTECTION"
    | "WASTE_MANAGEMENT"
    | "ROAD_MAINTENANCE"
    | "CIVIL_PROTECTION"
    | "EXTERNAL_MAINTAINER";
}

export interface MunicipalityUserResponse {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  role:
    | "ADMINISTRATOR"
    | "PUBLIC_RELATIONS"
    | "CULTURE_EVENTS_TOURISM_SPORTS"
    | "LOCAL_PUBLIC_SERVICES"
    | "EDUCATION_SERVICES"
    | "PUBLIC_RESIDENTIAL_HOUSING"
    | "INFORMATION_SYSTEMS"
    | "MUNICIPAL_BUILDING_MAINTENANCE"
    | "PRIVATE_BUILDINGS"
    | "INFRASTRUCTURES"
    | "GREENSPACES_AND_ANIMAL_PROTECTION"
    | "WASTE_MANAGEMENT"
    | "ROAD_MAINTENANCE"
    | "CIVIL_PROTECTION"
    | "EXTERNAL_MAINTAINER";
}
